### ISSUE TITLE
USD - RoW FX Rate not used

### ISSUE THREAD

**Issue by okarena** [fedoco/apple-slicer#1]
Hello,

Thank you first of all for the very useful script which helps me a lot to prepare correct invoices.

Unfortunately after results verifications I found that for some countries the Sales reports are not match to the Payment reports. These countries are like Albania, Algeria, Kenya, etc - all of them belongs to the so called by Apple "Rest of World" region.

As I found the reason for this issue is that the sales in these countries are made in USD, but the FX Rate which Apple use is not the USD (in the FX Rate table) but "USD - RoW" (Rest of World).

In the python script all FX Rates are read-in correctly, including "USD - RoW", but it is never used later for the calculations as in the sales reports for these countries Apple do not name currency as "USD - RoW", but just as USD.

Please let me know if it is clear what I've tried to explain and thank you in advance!

**Comment by okarena** [comment]
... in the Apps_Payments_Finance_Reports_Guide.pdf from Apple there is an explanation about different regions and also there mentioned that the actual country split on the regions are available in the Payments and Financial Reports  at the bottom of the Earnings pane. Here is this link, it is needed to be authorized in iTunes Connect to see it: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wo/9.0.0.11.5.0.9.3.1.25.1.3

**Comment by fedoco** [comment]
Could you please provide an anonymized sales report file and the corresponding payments table with the FX rates? I think I get the gist of the problem but I currently don't have any RoW sales to verify.

**Comment by okarena** [comment]
here it is: https://www.dropbox.com/s/128v6zheyz085wg/AFR_example.zip
Inside there are examples of the financial reports for EU, US and WW (world wide) and also correspondent currency_data.txt file.

**Comment by Elwisz** [comment]
@okarena Thanks for the notice, I think I got it fixed. Does it work for you?

**Comment by fedoco** [comment]
@okarena Thanks for notifying me, I think I got it fixed. Does it work for you?

**Comment by okarena** [comment]
Thank you very much for the fast response on this issue - I have tested your fix and now slice script works fine for me: all results looks correct now!
