### ISSUE TITLE
"Your sales" vs "Apple's sales"

### ISSUE THREAD

**Issue by carlosaviles** [fedoco/apple-slicer#10]
When you join the Apple Developer program and sign the contracts, you give Apple all the rights to sell your apps. So, technically, you are not selling any apps anywhere and there are no sells to be declared anywhere.

**Comment by fedoco** [comment]
The fact that Apple acts as a commission agent for you does not exempt you from proper invoicing. In addition, this script can be used to create recapitulative statements, which are also necessary for correct tax treatment in the EU – see README.
