### ISSUE TITLE
KeyError: 'HRK'

### ISSUE THREAD

**Issue by s1lviu** [fedoco/apple-slicer#11]
Hi! Back again with some error:

`Traceback (most recent call last):
  File "/Users/silviu/apple-slicer/./slicer.py", line 283, in <module>
    print_sales_by_corporation(sales, currencies, args.no_subtotals, args.only_subtotals)
  File "/Users/silviu/apple-slicer/./slicer.py", line 235, in print_sales_by_corporation
    exchange_rate, tax_factor = currency_data[country_currency]
KeyError: 'HRK'`
![image](https://user-images.githubusercontent.com/9863576/224682764-535c71f7-0e8f-4465-aaf8-f77262ec3df3.png)

The report looks like this:

![image](https://user-images.githubusercontent.com/9863576/224682665-5a71133a-0c5c-4e88-81a8-97e7521e1a56.png)

Thanks!

**Comment by fedoco** [comment]
In line 188 of the script, could you please (properly indented) insert the following code and try again:
`if amount == 0: continue`

**Comment by s1lviu** [comment]
Same

![image](https://user-images.githubusercontent.com/9863576/224685888-62c79325-eb31-4166-808e-591810b77855.png)

**Comment by fedoco** [comment]
Does your `financial_report.csv` contain a line for Croatia / HRK at all? If so, please show it to me.

**Comment by s1lviu** [comment]
![image](https://user-images.githubusercontent.com/9863576/224696342-69aaebea-d16b-408f-817c-e274a138e0d9.png)

**Comment by fedoco** [comment]
Your csv file seems to be very odd. The script stops processing after it encounters "empty" lines (meaning lines containing commas only) so what you could try is to compare your current csv file with the one from last month and adjust it accordingly so it doesn't contain any blank lines after line 4.

**Comment by s1lviu** [comment]
I have merged the Croatia line to the first bunch and deleted the second group, but now I have another error
![image](https://user-images.githubusercontent.com/9863576/224773489-afcab7b2-3a0b-4ce4-8788-6e76d4b15de3.png)

**Comment by fedoco** [comment]
I'm sorry, something seems to be very odd with your csv file. I've never encountered one that had different sections to begin with. Are you sure you downloaded the right one named `financial_report.csv`?

**Comment by s1lviu** [comment]
Yes... As usual. Also, it's the first time when the report has multiple sections. Maybe because Croatia turned to euro in 2023.
But even if I delete that entry, the amounts are far from the total paid amount.

**Comment by fedoco** [comment]
I'm afraid I can't help you then, sorry. I'd suggest to wait until the next month to see if it was only a one-time fluke and things go back to normal. If not, I would need the whole file(s) for further investigation.

**Comment by s1lviu** [comment]
Oh, I understand, no problem. I will then _randomly_ put the amount difference to the EU and hope it will be ok. Thank you!

**Comment by fedoco** [comment]
Seems like [that](https://mastodon.social/@chockenberry/110617136771898924) was the cause after all...

**Comment by fedoco** [comment]
Done.

**Comment by fedoco** [comment]
Done.
