### ISSUE TITLE
USD - Latin America and the Caribbean

### ISSUE THREAD

**Issue by mikakruschel** [fedoco/apple-slicer#13]
Hey @fedoco, thanks for this awesome tool. We just recently used it to create a free [Mac app](https://plutus.no-comment.xyz/) that uses the App Store Connect api to fetch the reports, parses them with our [swift port of this library](https://github.com/no-comment/plutus-financial-slicer), and exports invoices as PDFs. One user made us aware that there is an [issue](https://github.com/no-comment/plutus-financial-slicer/issues/1) with the currency conversion of USD in "Latin America and the Caribbean" (similarly to USD - Rest of the World). This is also an issue with your library.

**Comment by fedoco** [comment]
Thanks for the heads up, fixed in e9f469e. And good luck with your product – let's collaborate on similar issues in the future! :)
