### ISSUE TITLE
KeyError: 'USD - RoW' when doing a german report

### ISSUE THREAD

**Issue by codeon-nat** [fedoco/apple-slicer#3]
``` console
Traceback (most recent call last):
  File "./slicer.py", line 218, in <module>
    print_sales_by_corporation(sales, currencies)
  File "./slicer.py", line 187, in print_sales_by_corporation
    exchange_rate, tax_factor = currency_data[country_currency]
KeyError: 'USD - RoW'
```

In `slicer.py` there is 

```
            if "_WW." in filename and currency == "USD":
              currencies[countrycode] = "USD - RoW"
```

but in my german localized `financial_report.csv` the currency is actually `Rest der Welt (USD)`, so `slicer.py` fails. When I comment the two lines out, it works for me.

**Comment by fedoco** [comment]
@codeon-nat Could you please provide me with your `financial_report.csv`? I don't need the actual numbers, of course, so feel free to shuffle the monetary values.

**Comment by fedoco** [comment]
@codeon-nat  Are you still there? I have investigated the issue further and noticed that a screenshot of the leftmost column (the one listing region and currency) of some of your `financial_report.csv` which contain "Rest der Welt" sales would probably be enough for me to fix it.

**Comment by codeon-nat** [comment]
`cut '-d,' -f 1 financial_report.csv`

``` console
"iTunes Connect - Zahlungen und Finanzberichte  (Januar

Region (Währung)
Australien (AUD)
Kanada (CAD)
Schweiz (CHF)
Eurozone (EUR)
Schweden (SEK)
Nord- und Südamerika (USD)
Rest der Welt (USD)
```

**Comment by fedoco** [comment]
Thank you! One last request: Can you please confirm (or refute) that `Rest der Welt (USD)` is always placed below `Nord- und Südamerika (USD)` in reports of other months you may have downloaded?

**Comment by codeon-nat** [comment]
That's the only month I have with the new `financial_report.csv` and  a `_WW` file.

**Comment by fedoco** [comment]
Did you have other `_WW` files in past months? When you download their corresponding `financial_report.csv` today it will reflect the new format. My reason for still bothering you is that I need to make sure the order of the currencies is consistent as I unfortunately cannot parse the name of the currencies because Apple unfortunately decided to localize them as you noticed.

**Comment by codeon-nat** [comment]
Thx. No that was the only month BTW.

**Comment by fedoco** [comment]
Thank you for pointing out the issue! Please do not hesitate to open a new one should the script cease to work in the future.
