### ISSUE TITLE
Apple's incomplete `financial_report.csv` column count is no longer 11

### ISSUE THREAD

**Issue by codeon-nat** [fedoco/apple-slicer#5]
The slicer checks for incomplete reports by comparing the financial_report header column count with 11. But actually nowadays the reduced column count is 9. At least as I recently witnessed with September 2017. The unusal error message threw me off.

**Comment by fedoco** [comment]
I'm sorry, are you sure you're running the newest version of the script? The column count of line 1 currently should be 13 and indeed is, at least regarding to my recent reports.

**Comment by codeon-nat** [comment]
Seems not :( I thought I updated more recently than 6 months but apparently not. Sorry for the junk issue.

**Comment by fedoco** [comment]
No problem, and thanks for taking the time to report an issue! It's nice to know somebody else is actually using the script :)

**Comment by codeon-nat** [comment]
Oh it's really nice. Can't live w/o it. Or rather the tax office can't 🙄 😃
