### ISSUE TITLE
No distinction between European Union and Non-EU countries

### ISSUE THREAD

**Issue by Iomegan** [fedoco/apple-slicer#6]
Hi,

The readme says:

> the sum paid by Apple Distribution International must be split into revenue made in member states of the European Union and into revenue made in Non-EU countries

However, the script does not distinguish between European Union and Non-EU countries at all. Switzerland, China and others are included, which makes the sum for the Recapitulative Statement wrong. Compare with [https://exelerus.com/mobiledev/apple/](https://exelerus.com/mobiledev/apple/) when you include Switzerland in your financial reports.

Cheers

**Comment by fedoco** [comment]
As a member of Apple's Developer Program you do business with Apple's subsidiaries – not directly with retail customers. Hence, the individual customer's country of residence is irrelevant from a fiscal point of view. It seems that the developer behind the link you provided didn't get that quite right.

**Comment by Iomegan** [comment]
That makes sense, thanks.
