### ISSUE TITLE
[error] decimal.DivisionByZero 

### ISSUE THREAD

**Issue by s1lviu** [fedoco/apple-slicer#9]
Hi, thank you for this tool - using it for some months, but now I have encountered the following error:

`Traceback (most recent call last):
  File "/Users/silviu/apple-slicer/./slicer.py", line 268, in <module>
    currency_data = parse_currency_data(args.directory + '/' + currency_data_filename)
  File "/Users/silviu/apple-slicer/./slicer.py", line 143, in parse_currency_data
    tax_factor = Decimal(1.0) - abs(tax / amount_pre_tax)
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]`

Thank you!

**Comment by fedoco** [comment]
You'd need to provide your input file in order for me to debug that issue. Feel free to obfuscate / change anything that could identify your app – but please leave the numerical price values intact.

**Comment by s1lviu** [comment]
Thanks for the fast reply @fedoco 
Before sending you files, can the error be triggered by this line? I saw it was marked in red and maybe, maybe.
![image](https://user-images.githubusercontent.com/9863576/206175544-f357e2fd-63ca-4639-9014-f35faed5a1e1.png)
Thanks!

**Comment by fedoco** [comment]
Yeah, it looks like it's the culprit. It probably would be enough if you'd send me that line only.

**Comment by s1lviu** [comment]
`"Brazil (BRL)","0","0.00","0.00","0","0","-12.74","-12.74","0.19231","-2.45","USD",`

**Comment by fedoco** [comment]
Did you change that line in any way? It's missing a column. (Compared to a regular line, anyway.)

**Comment by s1lviu** [comment]
Nope.
![image](https://user-images.githubusercontent.com/9863576/206181642-4a254674-81ec-4e6f-918c-c3f6af423d81.png)

**Comment by fedoco** [comment]
(The number of columns is actually correct – my bad, sorry.)
Okay, it looks like the issue here is that you have to give back earnings to Apple because a Brazilian customer got a refund which didn't get balanced out by other earnings in Brazil. It's kind of amazing that this hasn't occurred in all the years the apple-slicer script exists. I'll fix it asap for you to test, probably later today. Thanks for reporting it!

**Comment by fedoco** [comment]
Oh, and could you please tell me if there is a file ending with `_BR.txt` in your App Store Connect downloads for the affected month?

**Comment by s1lviu** [comment]
Yes, it is `87727887_1022_BR_WHT.txt`

**Comment by fedoco** [comment]
I'm sorry, I need the content of that file, too. Please obfuscate any identifying strings and the "Apple Identifier" (column 11) if you want to.

**Comment by s1lviu** [comment]
[dld](https://www.icloud.com/notes/0deQP3q17eAXx1vmW0b-uDvzw#for_fedoco)
PS: tell me when you have it. thx

**Comment by fedoco** [comment]
"Unavailable. The owner stopped sharing, or you don't have permission to open it."

**Comment by s1lviu** [comment]
https://drive.google.com/file/d/1G8_dEyMtzq39J1jfDMEhe24YYs7yqOtB/view?usp=sharing

**Comment by fedoco** [comment]
Peak Apple. Grabbed it, thanks!

**Comment by fedoco** [comment]
Very odd. That isn't a typical "Payments & Financial Reports" file. Where did you download it? Was it really included with the other *.txt in the .zip?

**Comment by s1lviu** [comment]
> Very odd. That isn't a typical "Payments & Financial Reports" file. Where did you download it? Was it really included with the other *.txt in the .zip?

The files in .zip:
![image](https://user-images.githubusercontent.com/9863576/206191994-f92a3244-b680-4168-804d-0325dc9df5f5.png)

**Comment by fedoco** [comment]
Hmm, that is really quite strange as WHT information is normally part of what you can download with Apple's `reporter` Java tool or https://github.com/fedoco/itc-reporter. Anyway, I'll have a look into it and report back.

**Comment by s1lviu** [comment]
If you want, we can do an anydesk session later.

**Comment by fedoco** [comment]
Thanks, I don't think that will be necessary. One last question, though: Can you please search for the string `BRL` in the file `87727887_1022_ZZ.txt` and show me that whole line if there is a match?

**Comment by s1lviu** [comment]
> Thanks, I don't think that will be necessary. One last question, though: Can you please search for the string `BRL` in the file `87727887_1022_ZZ.txt` and show me that whole line if there is a match?

There is no match. Thanks!

**Comment by fedoco** [comment]
That's a bummer because it means that there isn't enough context in the files provided by Apple in order to apply a clean fix for that issue. Nevertheless, I of course updated the script so that it doesn't crash anymore and instead issues a warning with a note on what needs to be done manually. Please give it a test run.

By the way, I am pretty sure that I was wrong in my original analysis of the problem. It is simply not recognisable from the files why Apple withheld tax for Brazil without listing associated sales.

**Comment by s1lviu** [comment]
> That's a bummer because it means that there isn't enough context in the files provided by Apple in order to apply a clean fix for that issue. Nevertheless, I of course updated the script so that it doesn't crash anymore and instead issues a warning with a note on what needs to be done manually. Please give it a test run.
> 
> By the way, I am pretty sure that I was wrong in my original analysis of the problem. It is simply not recognisable from the files why Apple withheld tax for Brazil without listing associated sales.

Thanks for the quick fix @fedoco, I appreciate it!
The single issue for me now is what to do with that amount further for bookkeeping..

<img width="658" alt="image" src="https://user-images.githubusercontent.com/9863576/206233531-365b09d0-661d-4d5b-8022-9d2e226fe380.png">

**Comment by fedoco** [comment]
Well, thank _you_ for your help tracking down the issue!

As for the bookkeeping, the taxes reduce your revenue. Therefore I would simply include an invoice item of -2,45 € labelled "Taxes withheld" in the invoice to Apple LATAM and adjust its total accordingly.

**Comment by s1lviu** [comment]
No problem; it was my pleasure to collaborate with you and chase this edge case.
I hope to can contribute soon to the project somehow.
Also, thanks for the bookkeeping explanation; I was thinking the same but was unsure if it would be ok.
